language: node_js

cache: yarn

git:
    quiet: true

node_js:
    - '10'
    - '12'
    - '14'

# os
dist: focal

os:
    - windows

osx_image: xcode12.2

# See https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
    - YARN_GPG=no

# safelist
branches:
    only:
        - master
        - /^feat/.*$/
        - /^v\d*\.\d*\.\d*$/
        - /^dependabot/.*$/

script:
    - echo "Running tests against $(node -v)..."
    - cp .env.template .env.test
    - yarn test

jobs:
    fast_finish: true
    include:
        - stage: test
          name: linux deployment
          node_js: lts/*
          os: linux
          script:
              - sudo apt-get -y install poppler-data poppler-utils unrtf
              - cp .env.template .env.test
              - POPPLER_BINARY_PATH='/usr/bin' UNRTF_BINARY_PATH='/usr/bin' yarn test
        - stage: test
        name: macos deployment
        node_js: lts/*
        os: osx
        script:
            - brew install poppler unrtf
            - cp .env.template .env.test
            - POPPLER_BINARY_PATH='/usr/local/bin' UNRTF_BINARY_PATH='/usr/local/bin' yarn test
        - stage: test
          name: produce coverage
          node_js: lts/*
          os: windows
          script:
              - cp .env.template .env.test
              - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
              - rm -rf ./coverage
