language: node_js

cache: yarn

dist: bionic

node_js:
    - 'lts/*'
    - 'node'

os:
    - windows
    - linux

# See https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
    - YARN_GPG=no

# safelist
branches:
    only:
        - master
        - /^feat/.*$/
        - /^v\d*\.\d*\.\d*$/
        - /^dependabot/.*$/

script: echo "Running tests against $(node -v)..."

jobs:
    include:
        - stage: Produce Coverage
          node_js: lts/*
          os: windows
          script: cp .env.template .env.test && jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
