language: node_js

cache: yarn

dist: focal

git:
    quiet: true

node_js:
    - 'lts/*'
    - 'node'

os:
    - windows

# See https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/9
env:
    - YARN_GPG=no

# safelist
branches:
    only:
        - master
        - /^feat/.*$/
        - /^v\d*\.\d*\.\d*$/
        - /^dependabot/.*$/

script:
    - echo "Running tests against $(node -v)..."
    - cp .env.template .env.test
    - yarn test

jobs:
    include:
        - stage: test
          name: linux deployment
          node_js: lts/*
          os: linux
          script:
            - sudo apt-get -y install poppler-data poppler-utils
            - cp .env.template .env.test
            - POPPLER_BINARY_PATH='/usr/bin' yarn test
        - stage: test 
          name: produce coverage
          node_js: lts/*
          os: windows
          script:
            - cp .env.template .env.test
            - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
            - rm -rf ./coverage
