version: '3'
services:
    app:
        env_file:
            - .env
        build:
            context: .
        ports:
            - ${PORT:-3000}:${PORT:-3000}
        environment:
            NODE_ENV: production
            POPPLER_BINARY_PATH: '/usr/bin/'
