version: '3'
services:
    app:
        build:
            args:
                NODE_ENV: production
            context: .
        env_file: .env.production
        environment:
            POPPLER_BINARY_PATH: '/usr/bin/'
        ports:
            - 127.0.0.1:${PORT:-3000}:${PORT:-3000}
