name: CI

on:
    push:
        paths-ignore:
            - 'docs/**'
            - '*.md'
    pull_request:
        paths-ignore:
            - 'docs/**'
            - '*.md'

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x
            - name: Install
              run: yarn --immutable
            - name: Run ESLint
              run: yarn lint
            - name: Run Prettier
              run: yarn lint:prettier:ci

    macos:
        name: macOS Build
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]

        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: yarn --immutable
            - name: Run Tests
              env:
                  POPPLER_BINARY_PATH: /usr/local/bin
                  UNRTF_BINARY_PATH: /usr/local/bin
              run: |
                  brew install unrtf poppler
                  cp .env.template .env.test
                  yarn test-coverage
            - name: Coveralls Parallel
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel: true

    ubuntu:
        name: Ubuntu Build
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: yarn --immutable
            - name: Run Tests
              env:
                  POPPLER_BINARY_PATH: /usr/bin
                  UNRTF_BINARY_PATH: /usr/bin
              run: |
                  sudo apt-get -y install poppler-data poppler-utils unrtf
                  cp .env.template .env.test
                  yarn test-coverage
            - name: Coveralls Parallel
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel: true

    windows:
        name: Windows Build
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]

        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: yarn --immutable
            - name: Run Tests
              run: |
                  cp .env.template .env.test
                  yarn test-coverage
            - name: Coveralls Parallel
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel: true

    coverage:
        name: Aggregate Coverage Calculations
        needs: [macos, ubuntu, windows]
        runs-on: ubuntu-latest
        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true

    automerge:
        name: Automatically merge Dependabot pull requests
        needs: [macos, ubuntu, windows]
        runs-on: ubuntu-latest
        steps:
            - uses: fastify/github-action-merge-dependabot@v1
              if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
